spring:
  data:
    mongodb:
      uri: mongodb://mongodb-multiaz-staging:27017/prediction-storage-details
  datasource:
    url: jdbc:postgresql://postgresql-multiaz-staging:5432/prediction-storage
    username: prediction_storage_user
    password: prediction_storage_password