spring:
  application:
    name: prediction-orchestrator
  config:
    import: optional:configserver:http://config-service:8888
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8084

eureka:
  client: 
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
    