name: multiaz

services:

  config-service-multiaz: 
    build:
       context: ../backend/infrastructure/config-service/
       dockerfile: Dockerfile
    container_name: config-service-multiaz
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
    networks:
      - net-gateway
    volumes:
      - ../config:/config
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    
  service-discovery-multiaz:
    build: 
      context: ../backend/infrastructure/service-discovery/
      dockerfile: Dockerfile
    container_name: service-discovery-multiaz
    ports:
      - "8761:8761"
    networks:
      - net-gateway
      - net-prediction
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  

  # CORES
  api-gateway-multiaz:
    build: 
      context: ../backend/core/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway-multiaz
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - net-gateway
    depends_on:
      config-service-multiaz:
        condition: service_healthy
      service-discovery-multiaz:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    
  auth-service-multiaz:
    build:
      context: ../backend/core/auth-service
      dockerfile: Dockerfile
    container_name: auth-service-multiaz
    ports:
      - "8081:8081"
    environment:
      - AUTH_DB_USER=${AUTH_DB_USER}
      - POSTGRES_AUTH_PASS=${POSTGRES_AUTH_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_PROFILES_ACTIVE=dev
      - REDIS_PASS=${REDIS_PASS}
    networks:
      - net-gateway
      - net-database
    depends_on:
      config-service-multiaz:
        condition: service_healthy
      service-discovery-multiaz:
        condition: service_healthy
      mailhog-multiaz:
        condition: service_started
      postgresql-multiaz:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    
  model-registry-multiaz:
    build: 
      context: ../backend/core/model-registry
      dockerfile: Dockerfile
    container_name: model-registry-multiaz
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongodb-multiaz:27017/model_registry?authSource=admin
    networks:
      - net-gateway
      - net-database
    depends_on:
      config-service-multiaz:
        condition: service_healthy
      service-discovery-multiaz:
        condition: service_healthy
      mongodb-multiaz:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget","-q", "--spider", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  prediction-orchestrator-multiaz:
    build:
      context: ../backend/core/prediction-orchestrator
      dockerfile: Dockerfile
    container_name: prediction-orchestrator-multiaz
    ports:
      - "8084:8084"
    environment:
      - PREDICTION_ORCHESTRATOR_DB_USER=${PREDICTION_ORCHESTRATOR_DB_USER}
      - POSTGRES_PREDICTION_ORCHESTRATOR_PASS=${POSTGRES_PREDICTION_ORCHESTRATOR_PASS}
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - net-gateway
      - net-database
      - net-prediction
    depends_on:
      config-service-multiaz:
        condition: service_healthy
      service-discovery-multiaz:
        condition: service_healthy
      postgresql-multiaz:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget","-q", "--spider", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # IAs
  fake-news-detector-multiaz:
    build:
      context: ../backend/ia-services/fake-news-detector
      dockerfile: Dockerfile
    container_name: fake-news-detector-multiaz
    ports:
      - "8091:8091"
    networks:
      - net-prediction
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8091/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # MESSAGES
  rabbitmq-multiaz:
    image: rabbitmq:4-management
    container_name: rabbitmq-multiaz
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
      - vol-rabbitmq:/var/lib/rabbitmq
    networks:
      - net-message
  
  # STORAGE
  redis-multiaz:
    image: redis:8
    container_name: redis-multiaz
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]
    volumes:
      - vol-redis:/data
    networks:
      - net-database

  postgresql-multiaz:
    image: postgres:17
    container_name: postgresql-multiaz
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_AUTH_PASS=${POSTGRES_AUTH_PASS}
      - POSTGRES_MODEL_REGISTRY_PASS=${POSTGRES_MODEL_REGISTRY_PASS}
      - POSTGRES_PREDICTION_ORCHESTRATOR_PASS=${POSTGRES_PREDICTION_ORCHESTRATOR_PASS}
      - POSTGRES_SCHEDULER_PASS=${POSTGRES_SCHEDULER_PASS}
      - POSTGRES_DATASET_MANAGEMENT_PASS=${POSTGRES_DATASET_MANAGEMENT_PASS}
      - POSTGRES_NOTIFICATION_PASS=${POSTGRES_NOTIFICATION_PASS}
    volumes:
      - vol-postgresql:/var/lib/postgresql/data
      - ../scripts/postgres/init-databases.sh:/docker-entrypoint-initdb.d/initdatabases.sh
    networks:
      - net-database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  
  mongodb-multiaz:
    image: mongo:8
    container_name: mongodb-multiaz
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}  
    volumes:
      - vol-mongodb:/data/db
    networks:
      - net-database
  
  minio-multiaz:
    image: minio/minio:latest
    container_name: minio-multiaz
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASS}
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - vol-minio:/data
    networks:
      - net-database
  
  # MAIL
  mailhog-multiaz:
    image: mailhog/mailhog
    container_name: mailhog-multiaz
    ports:
      - "1025:1025" # STMP (Enviar email)
      - "8025:8025" # Web interface
    networks:
      - net-database
  
  # BACKUP
  backup-multiaz:
    build: 
      context: ../
      dockerfile: backend/infrastructure/backup-service/Dockerfile
    container_name: backup-multiaz
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASS=${POSTGRESQL_PASS}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASS=${MINIO_PASS}
    networks:
      - net-database
    depends_on:
      postgresql-multiaz:
        condition: service_healthy
      mongodb-multiaz:
        condition: service_started
      minio-multiaz:
        condition: service_started
      

volumes:
  vol-rabbitmq:
    driver: local
  vol-redis:
    driver: local
  vol-postgresql:
    driver: local
  vol-mongodb:
    driver: local
  vol-minio:
    driver: local

networks:
  net-gateway:
    driver: bridge
  net-prediction:
    driver: bridge
  net-message:
    driver: bridge
  net-database:
    driver: bridge
