version: '3.8'

services:

  config-service: 
    build:
       context: ../backend/infrastructure/config-service/
       dockerfile: Dockerfile
    container_name: config-service
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
    networks:
      - net-gateway
    volumes:
      - ../config:/config
    
  service-discovery:
    build: 
      context: ../backend/infrastructure/service-discovery/
      dockerfile: Dockerfile
    container_name: service-discovery
    ports:
      - "8761:8761"
    networks:
      - net-gateway
      - net-prediction

  # TEST
  test-service:
    build: 
      context: ../backend/test/test-service/
      dockerfile: Dockerfile
    container_name: test-service
    ports:
      - "9090:9090"
    networks:
      - net-gateway

networks:
  net-gateway:
    driver: bridge
  net-prediction:
    driver: bridge

