spring:
  datasource:
    url: jdbc:postgresql://postgresql-multiaz:5432/auth_db
    username: ${AUTH_DB_USER}
    password: ${POSTGRES_AUTH_PASS}

  data:
    redis:
      host: redis-multiaz
      port: 6379
      password: ${REDIS_PASS}

  jpa:
    hibernate:
      ddl-auto: none
      
  mail:
    host: mailhog-multiaz
    port: 1025

  flyway:
    enabled: true
    execute-in-transaction: false
    baseline-on-migrate: false
    validate-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET}

# loggging TRACER
logging:
  level:
    '[org.springframework.security]': TRACE 
