spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/prediction_orchestrator_db
    username: ${PREDICTION_ORCHESTRATOR_DB_USER}
    password: ${POSTGRES_PREDICTION_ORCHESTRATOR_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration